# Generated by Django 3.0.5 on 2020-04-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='assignment_group',
            field=models.IntegerField(choices=[(0, 'taskgroup'), (1, 'emailuser'), (2, 'ledgergroup')], default=-1),
        ),
        migrations.AlterField(
            model_name='taskescalationassignment',
            name='assignment_group',
            field=models.IntegerField(choices=[(0, 'taskgroup'), (1, 'emailuser'), (2, 'ledgergroup')], default=-1),
        ),
        migrations.AlterField(
            model_name='taskowner',
            name='assignment_group',
            field=models.IntegerField(choices=[(0, 'taskgroup'), (1, 'emailuser'), (2, 'ledgergroup')], default=-1),
        ),
    ]
