# Generated by Django 3.0.5 on 2020-05-29 01:23

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0004_auto_20200528_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCommentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/web/task-management/tasking/private-media/task_attachments/2020/05/29/09'), upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanagement.Task')),
                ('task_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanagement.TaskComment')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/web/task-management/tasking/private-media/task_attachments/2020/05/29/09'), upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanagement.Task')),
            ],
        ),
    ]
