# Generated by Django 3.0.5 on 2020-05-29 07:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0005_taskattachment_taskcommentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='filename',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='taskcommentattachment',
            name='filename',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='upload',
            field=models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/web/task-management/tasking/private-media/task_attachments/2020/05/29/15'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='taskcommentattachment',
            name='upload',
            field=models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/web/task-management/tasking/private-media/task_attachments/2020/05/29/15'), upload_to=''),
        ),
    ]
