# Generated by Django 3.0.5 on 2020-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0006_auto_20200529_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='extension',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='taskcommentattachment',
            name='extension',
            field=models.CharField(default='', max_length=50),
        ),
    ]
