# Generated by Django 2.2.12 on 2020-04-08 09:22

from django.db import migrations
import ledger_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailuser',
            managers=[
                ('objects', ledger_api.models.EmailUserManager()),
            ],
        ),
    ]
